## Variables and Data Types
- A variable is a name used to store data in a program. eg: age=21
- A data type defines what kind of values a variable hold. eg: str, int, float

In [1]:
age = 21
Name = "Arun"
Price = 12.3
print(age)
print(Name)
print(Price)

21
Arun
12.3


In [2]:
subjects = ["Math", "Science", "AI"]
print(subjects)

['Math', 'Science', 'AI']


## Input/Output
- input is data entered by the user into program.

In [3]:
name = input("Enter Your Name:")
age = input("Your age is:")
print(name)
print(age)

Enter Your Name: arun
Your age is: 21


arun
21


In [4]:
price = float(input("Enter Price: "))
print("Price", price)

Enter Price:  12


Price 12.0


## If–else conditions
- if- else decision-making statement that executes different blocks of codes based on whether a condition is True and False.

In [5]:
age = 20
if age >=18:
    print("You are eligible Vote")
else:
    print("You are not eligible to Vote ")

You are eligible Vote


In [6]:
num = 7
if num % 2 == 0:
    print("Even Number")
else:
    print("Odd Number")

Odd Number


In [7]:
marks = 85
if marks >=90:
    print("Grade A")
elif marks >=75:
    print("Grade B")
elif marks >=65:
    print("Grade C")
else:
    print("Sorry You are Fail")

Grade B


## Loop 
- A loop is used to repeat a block of code multiple times until a condition is met.

In [8]:
for i in range(5):
    print(i)

0
1
2
3
4


In [9]:
count = 1
while count <=5:
    print(count)
    count+=1

1
2
3
4
5


In [10]:
name = ['Arun', 'Prasad', 'Patel', 'Raju']
for name in name:
    print(name)

Arun
Prasad
Patel
Raju


In [11]:
for i in range(10):
    if i == 5:
        break
    print(i)

0
1
2
3
4


In [12]:
for i in range(5):
    if i == 2:
        continue
    print(i)

0
1
3
4


## Practice

In [13]:
guess_number = 7
guess = int(input("Guess the number (1-10): "))
if guess == guess_number:
    print("Correct! You guessed the number. ")
else:
    print("Wrong guess. try again! ")

Guess the number (1-10):  7


Correct! You guessed the number. 


In [ ]:
secert_number = 5
while True:
    guess=int(input("Guess the number (1-10): "))
    if guess == secert_number:
        print("Correct! You guessed the number.")
    else:
        print("Worng guess. try again! ")

Guess the number (1-10):  4


Worng guess. try again! 


Guess the number (1-10):  6


Worng guess. try again! 


Guess the number (1-10):  5


Correct! You guessed the number.


In [1]:
secret_number = 9
attempts = 0

while attempts < 3:
    guess = int(input("Guess the number (1–10): "))
    attempts += 1

    if guess == secret_number:
        print("You won in", attempts, "attempts!")
        break
else:
    print("Game over! The number was", secret_number)


Guess the number (1–10):  3
Guess the number (1–10):  12
Guess the number (1–10):  23


Game over! The number was 9


In [5]:
num1 = float(input("Enter first number: "))
num2 = float(input("Enter second number: "))
operator = input("Enter operator(+, -, *, /): ")
if operator == "+":
    print("Result:", num1 + num2)
elif operator == "-":
    print("Result", num2-num2)
elif operator == "*":
    print("Result", num1*num2)
elif operator == "/":
    if num2 !=0:
        print("Result", num1/num2)
    else:
        print("Error: Division by zero")
else:
    print("Invalid operator")

Enter first number:  12
Enter second number:  12
Enter operator(+, -, *, /):  +


Result: 24.0


In [ ]:
total_subjects = int(input("Enter number of subjects :"))
total_marks = 0
for i in range(total_subjects):
    marks = float(input(f"Enter marks for subject {i+1}:"))
    total_marks +=marks
    average = total_marks / total_subjects
    if average >=90:
        Grade = "A"
    elif average >=75:
        Grade = "B"
    elif average >=60:
        Grade = "C"
    else:
        Grade = "F"
        print("\n Total Marks:", total_marks)
        print("\n Average Marks:", average)
        print("\n Grade:", Grade)

Enter number of subjects : 67
Enter marks for subject 1: 78



 Total Marks: 78.0

 Average Marks: 1.164179104477612

 Grade: F


Enter marks for subject 2: 90



 Total Marks: 168.0

 Average Marks: 2.5074626865671643

 Grade: F


In [6]:
room_password='Arun'
attempt =0
while attempt < 3:
    guess =str(input("Enter your password(1-10): "))
    attempt +=1
    if guess == room_password:
        print("Your passwor is correct", attempt)
    else:
        print("worg password try agin")

Enter your password(1-10):  hsvsxbhx


worg password try agin


Enter your password(1-10):  Arun


Your passwor is correct 2


Enter your password(1-10):  7364


worg password try agin


In [7]:
room_password = "Arun"

for attempt in range(1, 4):
    guess = input("Enter your password: ")

    if guess == room_password:
        print("Your password is correct. Attempts:", attempt)
        break
    else:
        print("Wrong password, try again")

else:
    print("Too many wrong attempts. Access denied.")


Enter your password:  3363


Wrong password, try again


Enter your password:  arun


Wrong password, try again


Enter your password:  Arun


Your password is correct. Attempts: 3


## Python Data Structures

### List
- A list is a collection data type in python used to store multiple value in a single variable.
- ordered
- changeable
- differnt types of data

In [8]:
number = [10, 20, 30, 40, 50]
print(number)

[10, 20, 30, 40, 50]


In [10]:
name = ['Arun', 'Prasad', 'Patel', 'Rauthat']
print(name)

['Arun', 'Prasad', 'Patel', 'Rauthat']


In [11]:
student = ['Arun', 'True', 40, 'Patel', 100]
print(student)

['Arun', 'True', 40, 'Patel', 100]


## Tuple
- A tuple is a collection data type in python used to store multiple value in a single variable.
- ordered
- unchangeable
- differnt data types

In [12]:
number = (30, 320, 20, 10, 100)
print(number)

(30, 320, 20, 10, 100)


In [13]:
tuple = ('Arun', 'Prasad', 'Patel', 'Rauthat')
print(tuple)

('Arun', 'Prasad', 'Patel', 'Rauthat')


In [14]:
tuple = ('Arun', 10, 'Prasad', 20, 'Patel', 100)
print(tuple)

('Arun', 10, 'Prasad', 20, 'Patel', 100)


## set
- A set is a collection data type in Python used to store multiple values in a single variable.
- Unordered
- Unchangeable items
- Do not allow duplicate values

In [15]:
set = {1, 2, 3, 4, 5}
print(set)

{1, 2, 3, 4, 5}


In [16]:
data = {1, 2, 2, 3, 3, 5}
print(data)

{1, 2, 3, 5}


In [17]:
fruits = {"apple", "banana", "mango"}

fruits.add("orange")
fruits.remove("banana")

print(fruits)

{'apple', 'mango', 'orange'}


In [18]:
items = {"Arun", 21, True, 7.5}
print(items)

{'Arun', True, 21, 7.5}


## Dictionary
- A dictionary is a collection data type used to store data in key–value pairs.


In [20]:
student = {
    "name" : "Arun",
    "midle_name" : "Prasad",
    "last_name" : "Patel",
    "age" : 21,
    "mark" : 98
}
print(student)

{'name': 'Arun', 'midle_name': 'Prasad', 'last_name': 'Patel', 'age': 21, 'mark': 98}


In [21]:
print(student["name"])
print(student["age"])

Arun
21


In [23]:
student["age"]=22
print(student)

{'name': 'Arun', 'midle_name': 'Prasad', 'last_name': 'Patel', 'age': 22, 'mark': 98}


In [24]:
student["Grade"]='A'
print(student)

{'name': 'Arun', 'midle_name': 'Prasad', 'last_name': 'Patel', 'age': 22, 'mark': 98, 'Grade': 'A'}


In [25]:
for key, value in student.items():
    print(key, ":", value)

name : Arun
midle_name : Prasad
last_name : Patel
age : 22
mark : 98
Grade : A


In [26]:
info = {
    "name": "Arun",
    "is_student": True,
    "score": 90.5
}


In [27]:
data = {"a": 1, "a": 2}
print(data)


{'a': 2}


## Function
- A function is a block of reusable code that performs a specific task.
- Reduce code repetition
- Make programs easier to read and maintain

In [30]:
def greet():
    print("Hello, Wellcome to Python Program!")
greet()

Hello, Wellcome to Python Program!


In [32]:
def add(a, b):
    print(a+b)
add(10, 12)

22


In [33]:
def sub(a, b):
    print(a-b)
sub(200, 100)

100


In [34]:
def multiply(a, b):
    print(a*b)
multiply(12, 10)

120


In [36]:
def square():
    num = int(input("Enter a number:"))
    return num*num
print(square())

Enter a number: 2


4


## Lambda functions
- Lambda function is a small , anonymous function (a function without a name).

In [37]:
lambda arguments: expression

<function __main__.<lambda>(arguments)>

In [39]:
add = lambda a, b: a+b
print(add(4, 6))

10


In [41]:
square = lambda x: x*x
print(square(4))

16


In [42]:
numbers = [1, 2, 3, 4, 5]
squares = list(map(lambda x: x*x, numbers))
print(squares)

[1, 4, 9, 16, 25]


In [43]:
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
even = list(filter(lambda x: x%2==0, numbers))
print(even)

[2, 4, 6, 8, 10, 12]


In [51]:
def student_marks_system():
    name = input("Enter student name: ")

    marks = {}
    subjects = ["Math", "Science", "English"]

    for subject in subjects:
        marks[subject] = int(input(f"Enter marks for {subject}: "))

    total = sum(marks.values())
    percentage = total / len(subjects)

    if percentage >= 90:
        grade = "A+"
    elif percentage >= 80:
        grade = "A"
    elif percentage >= 70:
        grade = "B"
    elif percentage >= 60:
        grade = "C"
    else:
        grade = "Fail"

    print("\n--- Student Report ---")
    print("Name:", name)
    print("Marks:", marks)
    print("Total Marks:", total)
    print("Percentage:", percentage)
    print("Grade:", grade)


student_marks_system()


Enter student name:  arun
Enter marks for Math:  100
Enter marks for Science:  90
Enter marks for English:  80



--- Student Report ---
Name: arun
Marks: {'Math': 100, 'Science': 90, 'English': 80}
Total Marks: 270
Percentage: 90.0
Grade: A+


## File Handling
- File handling allows a program to create, read, write, and update files stored on your computer.

In [55]:
file = open("student.txt", "w")
file.write("Name: Arun\nMarks: 85")
file.close()

In [56]:
file = open("student.txt", "r")
content = file.read()
print(content)
file.close()


Name: Arun
Marks: 85


In [57]:
with open("data.txt", "w") as file:
    file.write("Hello Python")

with open("data.txt", "r") as file:
    print(file.read())


Hello Python


In [58]:
name = input("Enter name: ")
marks = input("Enter marks: ")

with open("marks.txt", "a") as file:
    file.write(f"Name: {name}, Marks: {marks}\n")

print("Data saved successfully!")


Enter name:  arun
Enter marks:  100


Data saved successfully!


## Exception Handling
-Exception handling is a way to handle errors that occur while a program is running, so the program doesn’t crash.

In [67]:
try:
    x = int(input("Enter a number: "))
    y = 10 / x
    print("Result:", y)
except ZeroDivisionError:
    print("Error: Cannot divide by zero!")
except ValueError:
    print("Error: Invalid input! Enter a number.")
finally:
    print("This block always runs.")


Enter a number:  12


Result: 0.8333333333333334
This block always runs.


In [70]:
try:
    with open("data.txt", "r") as file:
        content = file.read()
        print(content)
except FileNotFoundError:
    print("Error: File not found!")

Hello Python


In [69]:
try:
    num = int(input("Enter a number: "))
    result = 10 / num
except Exception as e:
    print("An error occurred:", e)

Enter a number:  12


## Class and Object
- A class is a blueprint for creating objects. It defines attributes (variables) and methods (functions).
- An object is an instance of a class. Each object can have its own values for attributes.

In [10]:
# Class definition
class Student:
    def __init__(self, name, age):
        self.name = name  # attribute
        self.age = age    # attribute

    def display(self):    # method
        print(f"Name: {self.name}, Age: {self.age}")

# Object creation
student1 = Student("Arun", 21)
student2 = Student("Sita", 22)

# Accessing method
student1.display()
student2.display()

Name: Arun, Age: 21
Name: Sita, Age: 22


## Inheritance
- Inheritance allows a class (child) inherit attribute and method from another class (parient).

In [9]:
# Parent class
class Person:
    def __init__(self, name):
        self.name = name

    def greet(self):
        print(f"Hello, my name is {self.name}")

# Child class
class Student(Person):
    def __init__(self, name, student_id):
        super().__init__(name)  # inherit name from Person
        self.student_id = student_id

    def show_id(self):
        print(f"My Student ID is {self.student_id}")

# Object creation
s = Student("Arun", 101)
s.greet()       # inherited method
s.show_id()     # child method


Hello, my name is Arun
My Student ID is 101


In [11]:
password = "Arun"

for i in range(3):
    guess = input("Enter password: ")
    if guess == password:
        print("Login successful")
        break
else:
    print("Account locked")


Enter password:  ahsvshs 
Enter password:  Arun


Login successful


In [12]:
with open("students.txt", "a") as f:
    name = input("Enter name: ")
    marks = input("Enter marks: ")
    f.write(f"{name}, {marks}\n")

Enter name:  arun
Enter marks:  90


In [13]:
class Student:
    def __init__(self, name, marks):
        self.name = name
        self.marks = marks

    def show(self):
        print(self.name, self.marks)

s1 = Student("Arun", 85)
s1.show()


Arun 85


## Linear Algebra
- Scalars, Vectors, Matrices
- Matrix Operations
- Eigenvalues & Eigenvectors


## A Scalar is a single number (a single value)

In [14]:
# Example
# a = 5
# b = 13.12
# c = -10

## Vectors
- A vector is a collection of number arranged in a single row or column.
- It can represent magnitude and direction.

In [15]:
vector = [1, 2, 3, 4]
print(vector)

[1, 2, 3, 4]


In [16]:
import numpy as np
v = np.array([1, 2, 3])
print(v)

[1 2 3]


## Matrix
- A matrix is 2D collection of numbers arranged in row or columns.

In [17]:
matrix = [
    [1, 2, 3],
    [4, 5, 6]
]
print(matrix)

[[1, 2, 3], [4, 5, 6]]


In [18]:
import numpy as np
m = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
print(m)

[[1 2 3]
 [4 5 6]]


## Matrix Operations
- Matrix operations are very important for Machine Learning, AI, and Data Science because data, weights, and transformations are all handled as matrices.
### Matrix Addition

In [19]:
import numpy as np

A = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])
B = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

C = A+B
print(C)

[[ 2  4  6  8]
 [10 12 14 16]]


In [20]:
# Matrix Subtraction
D = A-B
print(D)

[[0 0 0 0]
 [0 0 0 0]]


In [21]:
E = A*B
print(E)

[[ 1  4  9 16]
 [25 36 49 64]]


In [25]:
# Scalar Multiplication
E = 2*A
print(E)

[[ 2  4  6  8]
 [10 12 14 16]]


In [29]:
# Transpose of a Matrix
T = A.T
print(T)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [33]:
# Matrix Multiplication (Dot Product)
F = np.dot(A.T, B)
print(F)

[[26 32 38 44]
 [32 40 48 56]
 [38 48 58 68]
 [44 56 68 80]]


In [36]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

det = np.linalg.det(A)
print(det)

-2.0000000000000004


In [37]:
A_square = A[:, :2]   # take first 2 columns
det = np.linalg.det(A_square)
print(det)

-2.0000000000000004


In [38]:
# Use a Square Matrix
rank = np.linalg.matrix_rank(A)
print(rank)

2


In [39]:
u, s, vh = np.linalg.svd(A)
pseudo_det = np.prod(s)
print(pseudo_det)

1.9999999999999982


In [42]:
# det = np.linalg.det(A)
det = np.linalg.det(A)
print(det)

-2.0000000000000004


## Eigenvalues & Eigenvectors
- An eigenvector of a matrix is no non-zero vector that does not change direction when the matrix is applied to it only get scaled.
- An eigenvalue is the scalling factor by which the eigenvector is stretched or shrunk.
- A = square matrix
- v = eigenvector
- λ = eigenvalue
<center/>Av=λv

In [4]:
import numpy as np
A = ([
    [2, 1],
    [1, 2]
])
eigenvalues, eigenvectors =np.linalg.eig(A)
print("Eigenvalues: ")
print(eigenvalues)

print("\nEigenvectors: ")
print(eigenvectors)

Eigenvalues: 
[3. 1.]

Eigenvectors: 
[[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


# Probability & Statistics

In [5]:
# Mean (Average)
data = [10, 20, 30, 40]
mean = sum(data)/len(data)
print(mean)

25.0


In [6]:
# Median (Middle Value)
data = [10, 20, 30, 40, 50]
data.sort()
median = data[len(data)//2]
print(median)

30


In [7]:
from statistics import mode
data = [1, 2, 3, 4]
print(mode(data))

1


In [9]:
# Variance
import numpy as np
data = np.array([20, 30, 40])
variance = np.var(data)
print(variance)

66.66666666666667


In [10]:
# Standard Deviation
std = np.std(data)
print(std)

8.16496580927726


In [12]:
# Normal Distribution
import numpy as np

data = np.random.normal(50, 10, 1000)
print(np.mean(data), np.std(data))

50.15723226735441 10.3632628956325


## Probability Distributions
- A probability distribution describes how probabilities are distributed over possible values of a random variable.

In [13]:
import numpy as np

data = np.random.binomial(1, 0.7, 10)
print(data)

[1 1 1 1 0 1 1 1 1 1]


In [14]:
import numpy as np

data = np.random.binomial(10, 0.5, 5)
print(data)


[4 3 7 7 7]


In [15]:
import numpy as np

data = np.random.poisson(3, 10)
print(data)

[5 5 2 0 0 1 3 2 3 3]


In [16]:
import numpy as np

data = np.random.normal(50, 10, 1000)
print(np.mean(data), np.std(data))

50.018551514353334 10.091521868289341


In [17]:
import numpy as np

data = np.random.uniform(1, 10, 5)
print(data)


[7.315684   4.7857138  4.27814735 6.48705492 5.36097223]


In [18]:
import numpy as np

data = np.random.exponential(2, 5)
print(data)

[1.98298316 1.87259836 1.97598113 1.88188793 0.35265333]


## Bayes Theorem
- Bayes’ Theorem describes how to update the probability of an event based on new evidence.

In [20]:
P_D = 0.01
P_pos_given_D = 0.99
P_pos_given_notD = 0.01

P_pos = (P_pos_given_D * P_D) + (P_pos_given_notD * (1 - P_D))

P_D_given_pos = (P_pos_given_D * P_D) / P_pos
print(P_D_given_pos)

0.5


## Correlation & Covariance
- Covariance measures how two variables change together.
- Correlation measures strength and direction of the relationship between two variables.

In [21]:
import numpy as np

x = np.array([1, 2, 3, 4])
y = np.array([2, 4, 6, 8])

cov = np.cov(x, y)
print(cov)


[[1.66666667 3.33333333]
 [3.33333333 6.66666667]]


In [22]:
corr = np.corrcoef(x, y)
print(corr)

[[1. 1.]
 [1. 1.]]


## Calculus
- Calculus is a branch of mathematics that deals with rates of change and accumulation.
- A derivative measures how fast a value changes.

In [26]:
import sympy as sp
x = sp.symbols('x')
f = x**2                                #    dy/dx
df = sp.diff(f, x)                      # f(x,y)=x2+y2
print(df)

2*x


In [28]:
# An integral represents area under the curve.
integral = sp.integrate(f, x)
print(integral)                       

x**3/3


In [30]:
# Limits
import sympy as sp

x = sp.symbols('x')
f = (x**2 - 4) / (x - 2)
limit = sp.limit(f, x, 2)
print(limit)

4


In [31]:
import sympy as sp

x = sp.symbols('x')
f = x**3 + 2*x
df = sp.diff(f, x)
print(df)

3*x**2 + 2


In [32]:
# A partial derivative measures how a function changes with respect to one variable, while keeping other variables constant.
import sympy as sp

x, y = sp.symbols('x y')
f = x**2 * y + y**3

dx = sp.diff(f, x)
dy = sp.diff(f, y)

print("∂f/∂x =", dx)
print("∂f/∂y =", dy)

∂f/∂x = 2*x*y
∂f/∂y = x**2 + 3*y**2


In [33]:
# Gradient Descent is an optimization algorithm used to minimize a function (usually a loss/cost function) by moving in the opposite direction of the gradient.
x = 10
lr = 0.1

for i in range(10):
    grad = 2 * x
    x = x - lr * grad
    print(x)

8.0
6.4
5.12
4.096
3.2768
2.62144
2.0971520000000003
1.6777216000000004
1.3421772800000003
1.0737418240000003
